server:
  port: 8083

spring:
  application:
    name: ai-risk-evaluator

  threads:
    virtual:
      enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092} # Default to local docker kafka network

    consumer:
      group-id: risk-evaluator-group
      auto-offset-reset: earliest
      max-poll-records: 1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.paymentgateway.risk.model.IncomingPaymentEvent
        max.poll.interval.ms: 900000

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  ai:
    anthropic:
      api-key: ${SPRING_AI_ANTHROPIC_API_KEY}
      chat:
        options:
          model: claude-sonnet-4-6
          temperature: 0.1
          max-tokens: 250

# Observability Configurations
management:
  tracing:
    sampling:
      probability: 1.0 # 100% sampling for development/debugging. Reduce in Prod (e.g., 0.1)
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://zipkin:9411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus # Expose metrics endpoints